# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.12'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: qZJiLh9b2CIf+fqZodTvdgZnSObGpf+JnUgpt0+ONvyaBgz8kNnXtV7y6j8gyLWbu3nNVDWLDDl2DOxjzshdXST2Yy2uCOifrz7Cj0Ijfak+ayf56zvmffAEV10KmQnhdEVYLTfgaZtGOmR2AUJBAVV4GoEgURu5kaAWYRnhiAgf/IDx9NxGpT4fzUjaBOghdt0dhYCELUWgQpbxn5LAFWGthxoyy1ac8xEeBAlTV+Kok2Ayuyxu1Xjr/+ReAL/7H/OemG7rTNYeNCLtQyk84Og7JEtrw/SzjWY8L1iq+NxKVkLKjKSqrbFPjR95jElB1gQPrqEL1b9e1r/fxMp48sb31nqa0yj2mpusx7IyZm29rTUwxwyNCrL4rhem1m9dPqj3S806NTHr+6yY990/hTWG9K7GRY0+XrigGY5k2DoMTTnb5RT6ErdbEmLgkA445AwWnbYnYl2W0qq7dSkemIDBlTMzc7SuhCgzMlT/H/VdUbTCCQcTbUqAp/NOzrlbzjGA9qUiKbG2sVmlrSce77IhlLDQcjDHEV8IjST1LgtmfC/Cv+TcPpIVU37lqfFD7qO2vxetwg8g7nLZ7pTfvY7429SqV6SYs10loplYeVMbg8KUs6D4hIOLCSKGxh5WUj8HdpeqatA7SEMKck25rHZMpVMJ2GxmrIclZT8cqu4=
    # SAUCE_TOKENS
    - secure: c52toG+wqL+LAvbtTsjKjHAI/Kbg9yY1Dm+U+VVXTIR4q3dPn8sKg6g6mffkh7oj3FzJHHD+ml1Nh5lmGFBBH0Q8BldH1Rv0X8/XrPDewS387KSwve1aag65RTb7qbq99/Zev/Z0aqDTMiPF7J9alMjHNoIjsvmozPWyyZvzN74LztubJqzjqjwnhCqoCmeRgF1SFVZmTNMDCBANOA4FRfGmdD56XPjQd6UJOv1c0fwON4fok11dRGu2n0h6F0ysE5BW7wXUWe0agSEB2wEvr9sjvJ8STHxljAwNHvSkGYEqnuzerXDhiIiSJyaR3d0F/pgltlQNOCcCtIIH/Y5Iix+fehOHuton1DACkQkcuNG1puNybghuZnEHpyKy3bIlovXhMLfDfXcIK3LkLLhQbGx2eMwaGOsBlPJMv3IWrVO6VYSvdwyGQxkS/5JFr1AymfbcDRsqX00Q+IdgTNpS0DwF9Tlzl8F7UBJ02fstBGN7MVoe7wvSJ+4G3urAjo4Ui5+4uFP5CO7H8EH7Yn3ObHYb1Zv45aewcXVi34BBgCp1W3kyFTB19H5oEuWDucUfMpsa3rsXTsvfm5V6V+1pNgFcvsoM4BO+RL/ZUzeqd7dK43T7XySQOSubj5zzDB8Wl8xg+EyRXmh0Q6E+aPrwIuAFVePqS6KC8FSnki+p3BE=
    - secure: CMykLTWBBsm4EEBdiuoEO420XZj1uq1y36qoB1Kt7abN3ViaRSpn5LaYxBoC69xQwvMEa4fNeQYXyZuVGPMa66DSwqpRbPQmjNsLQEEoY0AJ17aaK/2k+EsFVm0mjwjr9YECbktZWdxXmDNOYEzIGSUXjREZQ5a4XtSbTS5T/gj8PD/ZVKcTe32Wq02AypgAkPYWEzeXCnsV0X78UOoiUvv4rVh80XQJkbPGWQ8NI8Y75o6HThjwjeOqi+WXS00CAUXg21bzZJV8HqwdVfeHISnN2XZIiVgMDqpHf/8nL3v/9brPnAIQjUCrhQ9joMmziYVD+AmpAMyT+rZY9OaafRgNf9gZLLbKeaCqb2d9bMAakwwOiDvENy4X5XzuuDtbkVyLbDWyJHzzDAmijxQ6sGei0os4MoOq+xZWBGtdyB26tzRwb3Bk10qFfZ1goyFA1GDsO9SOL72KZ+SIMeAM8NeVmRBbIIgi9uelSFxWmem8SVT6xPquCopBqQTj5VT+RhH26TeDAH7BIx0lyFpDD5sbxMCZxDCt33WudyLC9sQA0Vdny1weJAUTcBI0Epak9zWA+EWZZlb72SSmy8TaFFuvLHKdHzYnO2fbdxZs50UrJ8F71XlGcwxEe7l6PXDmkZi0Md+sbe3dSMEharV3Vrr9BoZQzPLdGn7440ZyzP0=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: mvWXlBosxsrZITp2xsdS6crHKp6l9Ulrz2+CPUxMZ/qMZbC1h9RN3eNf27chfi2PNZv7mWt73GJ6q2juhohi3fx6mKsa8CA9+Htl5VrKmhH+O72YcmwVJJXiI7BBhZ0Iv5I/fAc25mERPzZvdirfkcYLs9UW48SDzmeAG6eU9qf+dU4bJh2Tx6iEcjVMuoIGm88U8HmOv5vjPbOqMDbXDPwQulN7mksXJeTqwe4bSnVmwL+w3rHTqhUFQilWb/+V0CoqoDraDdAEBPyVA0VAoHkal/0Sp6vXHY/nIh4KhWRc9feEOwHRINZTP2iTzIlIB0UbjDWk5fn0nMr/zbWx6eby1DScawwanRdDQcVykvyb56xbeT71aDgeU06oUyftYSghJWBToAVr2AwuGctU4p9/yxMfUuGFIMeld5OVr/W4bYbSutEyRiQM/V5K7AaTJ46uaRPFlPRgle9ShtthtkWQFpSmB3B4komPzB3p5r/KQG+iTje2a1lcOrJQnGSzfVAv8wkhaqGZ3Av7tFmnho9nAr3LuMJIP81Z2LBOIi7hmaz95yWR2r34LhP3lAVhOVJ1GiYRTV1CwiFyCfkCl54mj+a6nGstY2My5aoNTr8xClUBHdiIXI6WYpXrTRZN/9aDCpsg+g9xXNkl6d0OcKpaxom0djByjUpVmWpNuis=

# Cloud testing
after_deploy:
  - npm install
  - npm run test-cloud
